server:
  port: 8585
spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thanus88/abs-configuration-service.git